/* Run as MySQL root user. */
DROP DATABASE IF EXISTS `ngembryo`;
CREATE DATABASE ngembryo;

USE ngembryo;

DROP TABLE IF EXISTS `layer`;
CREATE TABLE layer (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  summary TEXT NULL,
  description TEXT NULL,
  PRIMARY KEY(id)
);

DROP TABLE IF EXISTS `2Dmarker`;
CREATE TABLE 2Dmarker (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  x INTEGER UNSIGNED NOT NULL,
  y INTEGER UNSIGNED NOT NULL,
  scale INTEGER UNSIGNED NOT NULL,
  dst FLOAT NOT NULL,
  yaw FLOAT NOT NULL,
  rol FLOAT NOT NULL,
  pit FLOAT NOT NULL,
  label VARCHAR(255) NOT NULL,
  description TEXT NULL,
  PRIMARY KEY(id)
);

DROP TABLE IF EXISTS `2Dpolyline`;
CREATE TABLE 2Dpolyline (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  x INTEGER UNSIGNED NOT NULL,
  y INTEGER UNSIGNED NOT NULL,
  2Dregion_id INTEGER UNSIGNED NOT NULL,
  rank INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(id, 2Dregion_id),
  INDEX 2Dpolyline_FKIndex1(2Dregion_id)
);

DROP TABLE IF EXISTS `2Dregion`;
CREATE TABLE 2Dregion (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  scale INTEGER UNSIGNED NOT NULL,
  dst FLOAT NOT NULL,
  yaw FLOAT NOT NULL,
  rol FLOAT NOT NULL,
  pit FLOAT NOT NULL,
  tl_x INTEGER UNSIGNED NOT NULL,
  tl_y INTEGER UNSIGNED NOT NULL,
  br_x INTEGER UNSIGNED NOT NULL,
  br_y INTEGER UNSIGNED NOT NULL,
  label VARCHAR(255) NOT NULL,
  description TEXT NULL,
  PRIMARY KEY(id)
);

DROP TABLE IF EXISTS `3Dmarker`;
CREATE TABLE 3Dmarker (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  x INTEGER UNSIGNED NOT NULL,
  y INTEGER UNSIGNED NOT NULL,
  z INTEGER UNSIGNED NOT NULL,
  scale INTEGER UNSIGNED NOT NULL,
  label VARCHAR(255) NOT NULL,
  description TEXT NULL,
  PRIMARY KEY(id)
);

DROP TABLE IF EXISTS `resource`;
CREATE TABLE resource (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NULL,
  abstract TEXT NULL,
  url TEXT NULL,
  PRIMARY KEY(id)
);

DROP TABLE IF EXISTS `2DmarkerResource`;
CREATE TABLE 2DmarkerResource (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  aid INTEGER UNSIGNED NOT NULL,
  rid INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(id),
  INDEX (aid, rid),
  FOREIGN KEY (aid) REFERENCES 2Dmarker (id),
  FOREIGN KEY (rid) REFERENCES resource (id)
);

DROP TABLE IF EXISTS `2DregionResource`;
CREATE TABLE 2DregionResource (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  aid INTEGER UNSIGNED NOT NULL,
  rid INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(id),
  INDEX (aid, rid),
  FOREIGN KEY (aid) REFERENCES 2Dregion (id),
  FOREIGN KEY (rid) REFERENCES resource (id)
);

DROP TABLE IF EXISTS `layer2Dmarker`;
CREATE TABLE layer2Dmarker (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  aid INTEGER UNSIGNED NOT NULL,
  lid INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(id),
  INDEX (aid, lid),
  FOREIGN KEY (aid) REFERENCES 2Dmarker (id),
  FOREIGN KEY (lid) REFERENCES layer (id)
);

DROP TABLE IF EXISTS `layer2Dregion`;
CREATE TABLE layer2Dregion (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  aid INTEGER UNSIGNED NOT NULL,
  lid INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(id),
  INDEX (aid, lid),
  FOREIGN KEY (aid) REFERENCES 2Dregion (id),
  FOREIGN KEY (lid) REFERENCES layer (id)
);

DROP TABLE IF EXISTS `model`;
CREATE TABLE model (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  description TEXT NULL,
  stack TEXT NOT NULL,
  server TEXT NOT NULL,
  webpath TEXT NOT NULL,
  fspath TEXT NOT NULL,
  initialdst INTEGER UNSIGNED NOT NULL,
  assayid TEXT NULL,
  imgtitle TEXT NULL,
  external TEXT NULL,
  tileframe BOOLEAN NOT NULL,
  locator BOOLEAN NOT NULL,
  sectionplane BOOLEAN NOT NULL,
  sp_src TEXT NOT NULL,
  sp_inc INTEGER UNSIGNED NOT NULL,
  sp_numpit INTEGER UNSIGNED NOT NULL,
  sp_numyaw INTEGER UNSIGNED NOT NULL,
  sp_title TEXT NULL,
  sp_bgcolor TEXT NULL,
  PRIMARY KEY(id)
);

DROP USER 'ngembryo'@'localhost';
CREATE USER 'ngembryo'@'localhost' IDENTIFIED BY 'ngembryo';
GRANT ALL PRIVILEGES ON ngembryo.* TO 'ngembryo'@'localhost';
