/* Run as MySQL root user. */
CREATE DATABASE ngembryo;

USE ngembryo;

CREATE TABLE 2Dmarker (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  x INTEGER UNSIGNED NOT NULL,
  y INTEGER UNSIGNED NOT NULL,
  scale INTEGER UNSIGNED NOT NULL,
  dst FLOAT NOT NULL,
  yaw FLOAT NOT NULL,
  rol FLOAT NOT NULL,
  pit FLOAT NOT NULL,
  label VARCHAR(255) NOT NULL,
  description TEXT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE 2Dpolyline (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  x INTEGER UNSIGNED NOT NULL,
  y INTEGER UNSIGNED NOT NULL,
  2Dregion_id INTEGER UNSIGNED NOT NULL,
  rank INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(id, 2Dregion_id),
  INDEX 2Dpolyline_FKIndex1(2Dregion_id)
);

CREATE TABLE 2Dregion (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  scale INTEGER UNSIGNED NOT NULL,
  dst FLOAT NOT NULL,
  yaw FLOAT NOT NULL,
  rol FLOAT NOT NULL,
  pit FLOAT NOT NULL,
  tl_x INTEGER UNSIGNED NOT NULL,
  tl_y INTEGER UNSIGNED NOT NULL,
  br_x INTEGER UNSIGNED NOT NULL,
  br_y INTEGER UNSIGNED NOT NULL,
  label VARCHAR(255) NOT NULL,
  description TEXT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE 3Dmarker (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  x INTEGER UNSIGNED NOT NULL,
  y INTEGER UNSIGNED NOT NULL,
  z INTEGER UNSIGNED NOT NULL,
  scale INTEGER UNSIGNED NOT NULL,
  label VARCHAR(255) NOT NULL,
  description TEXT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE resource (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NULL,
  abstract TEXT NULL,
  url TEXT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE 2DmarkerResource (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  aid INTEGER UNSIGNED NOT NULL,
  rid INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(id),
  INDEX (aid, rid),
  FOREIGN KEY (aid) REFERENCES 2Dmarker (id),
  FOREIGN KEY (rid) REFERENCES resource (id)
);

CREATE TABLE 2DregionResource (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  aid INTEGER UNSIGNED NOT NULL,
  rid INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(id),
  INDEX (aid, rid),
  FOREIGN KEY (aid) REFERENCES 2Dregion (id),
  FOREIGN KEY (rid) REFERENCES resource (id)
);

CREATE USER 'ngembryo'@'localhost' IDENTIFIED BY 'ngembryo';
GRANT ALL PRIVILEGES ON ngembryo.* TO 'ngembryo'@'localhost';
